* About
  These are all my elisp files, functions and config, except for the [[https://github.com/Viglioni/spacemacs/blob/master/.spacemacs][.spacemacs]] file.
  More general config instructions about how to use my spacemacs repo, which this repo is a submodule of, you can find at [[https://github.com/Viglioni/spacemacs/blob/master/README.md][here]].

** Files and dirs
*** laurisp.el
    loads all my files, all of them have the form `l-*.el`.* 
*** core
    has all my core functions, /i.e./, what I use to define my other functions.
*** lazy-funcs
    has all the functions I created for my emacs
*** configs
    has all the main config I use, bindings, hooks etc
*** lazy-configs
    these files here are loaded only when they are necessary
*** external
    external libs I installed manually
*** snippets
    all the snippets and snippets hierarchy I created/defined
*** test
    well this one is easy, right?
* Testing
  To run tests we use [[https://github.com/jorgenschaefer/emacs-buttercup/][buttercup]] and [[https://github.com/cask/cask][cask]].

  In the root of this project:

*** To install buttercup dependencies
    #+begin_src shell
      $ cask install 
    #+end_src

*** To run tests
    #+begin_src shell
      $ cask exec buttercup
    #+end_src

* Licence
  This project is free and it will always be.
  [[https://www.gnu.org/licenses/gpl-3.0.en.html][GPL-3]]

