;;
;; @author Laura Viglioni
;; 2020
;; GNU Public License 3.0
;;

;;
;; icons-definitions related functions
;;


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
                                        ;          Javascript family          ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(setq js-colour 'all-the-icons-yellow)
(setq
 js-icons
 (list
  (icon-def "\\.styles\\.js$" "pencil" js-colour 'all-the-icons-octicon)
  (icon-def "theme\\.js$" "pencil" js-colour 'all-the-icons-octicon)
  (icon-def "\\.spec\\.js$" "test-js" js-colour)
  (icon-def "\\.test\\.js$" "test-js" js-colour)
  (icon-def "\\.js$" "javascript" js-colour 'all-the-icons-alltheicon)
  (icon-def "\\.spec\\.jsx$" "test-react" js-colour)
  (icon-def "\\.test\\.jsx$" "test-react" js-colour)
  (icon-def "\\.jsx$" "jsx-2" js-colour)))

(setq ts-colour 'all-the-icons-purple)
(setq ts-icons
      (list
       (icon-def "\\.styles\\.ts$" "pencil" ts-colour 'all-the-icons-octicon)
       (icon-def "theme\\.ts$" "pencil" ts-colour 'all-the-icons-octicon)
       (icon-def "\\.spec\\.ts$" "test-typescript" ts-colour)
       (icon-def "\\.test\\.ts$" "test-typescript" ts-colour)
       (icon-def "\\.d\\.ts$" "typescript" ts-colour)
       (icon-def "\\.ts$" "typescript" ts-colour)
       (icon-def "\\.spec\\.tsx$" "test-typescript" ts-colour)
       (icon-def "\\.test\\.tsx$" "test-typescript" ts-colour)
       (icon-def "\\.tsx$" "tsx-alt" ts-colour)))

(setq
 other-js-family-icons
 '(("\\.node" all-the-icons-alltheicon "nodejs" :height 1.0 :face all-the-icons-green)
   ("\\.babelrc$" all-the-icons-fileicon "babel" :face all-the-icons-yellow)
   ("\\.npmignore" all-the-icons-fileicon "npm" :face all-the-icons-dred)
   ("^package.json$" all-the-icons-fileicon "npm" :face all-the-icons-red)
   ("^package.lock.json$" all-the-icons-fileicon "npm" :face all-the-icons-dred)
   ("^yarn\\.lock" all-the-icons-fileicon "yarn" :face all-the-icons-blue-alt)
   ("\\.es[0-9]$" all-the-icons-alltheicon "javascript" :height 1.0 :v-adjust 0.0 :face all-the-icons-yellow)
   ("\\.njs$" all-the-icons-alltheicon "nodejs" :height 1.2 :face all-the-icons-lgreen)
   ("\\.vue$" all-the-icons-fileicon "vue" :face all-the-icons-lgreen)
   ("\\.react" all-the-icons-alltheicon "react" :height 1.1 :face all-the-icons-lblue)))

(setq js-family-icons
      (append
       js-icons
       ts-icons
       other-js-family-icons))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
                                        ;  All other icons not organized yet  ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(setq
 other-icons
 '(("\\.tags" all-the-icons-octicon "tag" :height 1.0 :v-adjust 0.0 :face all-the-icons-blue)
 ("^TAGS$" all-the-icons-octicon "tag" :height 1.0 :v-adjust 0.0 :face all-the-icons-blue)
 ("\\.log" all-the-icons-octicon "bug" :height 1.0 :v-adjust 0.0 :face all-the-icons-maroon)
 ("\\.key$" all-the-icons-octicon "key" :v-adjust 0.0 :face all-the-icons-lblue)
 ("\\.pem$" all-the-icons-octicon "key" :v-adjust 0.0 :face all-the-icons-orange)
 ("\\.p12$" all-the-icons-octicon "key" :v-adjust 0.0 :face all-the-icons-dorange)
 ("\\.crt$" all-the-icons-octicon "key" :v-adjust 0.0 :face all-the-icons-lblue)
 ("\\.pub$" all-the-icons-octicon "key" :v-adjust 0.0 :face all-the-icons-blue)
 ("\\.gpg$" all-the-icons-octicon "key" :v-adjust 0.0 :face all-the-icons-lblue)
 ("^TODO$" all-the-icons-octicon "checklist" :v-adjust 0.0 :face all-the-icons-lyellow)
 ("^LICENSE$" all-the-icons-octicon "book" :height 1.0 :v-adjust 0.0 :face all-the-icons-blue)
 ("^readme" all-the-icons-octicon "book" :height 1.0 :v-adjust 0.0 :face all-the-icons-lcyan)
 ("\\.fish" all-the-icons-alltheicon "terminal" :face all-the-icons-lpink)
 ("\\.zsh" all-the-icons-alltheicon "terminal" :face all-the-icons-lcyan)
 ("\\.sh" all-the-icons-alltheicon "terminal" :face all-the-icons-purple)
 ("\\.bashrc$" all-the-icons-alltheicon "script" :height 0.9 :face all-the-icons-dpink)
 ("\\.bowerrc$" all-the-icons-alltheicon "bower" :height 1.0 :v-adjust 0.0 :face all-the-icons-silver)
 ("^bower.json$" all-the-icons-alltheicon "bower" :height 1.0 :v-adjust 0.0 :face all-the-icons-lorange)
 ("\\.ini$" all-the-icons-octicon "settings" :v-adjust 0.0 :face all-the-icons-yellow)
 ("\\.eslintignore" all-the-icons-fileicon "eslint" :height 0.9 :face all-the-icons-purple)
 ("\\.eslint" all-the-icons-fileicon "eslint" :height 0.9 :face all-the-icons-lpurple)
 ("\\.git" all-the-icons-alltheicon "git" :height 1.0 :face all-the-icons-lred)
 ("nginx" all-the-icons-fileicon "nginx" :height 0.9 :face all-the-icons-dgreen)
 ("apache" all-the-icons-alltheicon "apache" :height 0.9 :face all-the-icons-dgreen)
 ("^Makefile$" all-the-icons-fileicon "gnu" :face all-the-icons-dorange)
 ("\\.mk$" all-the-icons-fileicon "gnu" :face all-the-icons-dorange)
 ("\\.dockerignore$" all-the-icons-fileicon "dockerfile" :height 1.2 :face all-the-icons-dblue)
 ("^\\.?Dockerfile" all-the-icons-fileicon "dockerfile" :face all-the-icons-blue)
 ("^Brewfile$" all-the-icons-faicon "beer" :face all-the-icons-lsilver)
 ("\\.xml$" all-the-icons-faicon "file-code-o" :height 0.95 :face all-the-icons-lorange)
 ("^stack.*.json$" all-the-icons-alltheicon "aws" :face all-the-icons-orange)
 ("^serverless\\.yml$" all-the-icons-faicon "bolt" :v-adjust 0.0 :face all-the-icons-yellow)
 ("\\.[jc]son$" all-the-icons-octicon "settings" :v-adjust 0.0 :face all-the-icons-yellow)
 ("\\.ya?ml$" all-the-icons-octicon "settings" :v-adjust 0.0 :face all-the-icons-dyellow)
 ("\\.pkg$" all-the-icons-octicon "package" :v-adjust 0.0 :face all-the-icons-dsilver)
 ("\\.rpm$" all-the-icons-octicon "package" :v-adjust 0.0 :face all-the-icons-dsilver)
 ("\\.elc$" all-the-icons-octicon "file-binary" :v-adjust 0.0 :face all-the-icons-dsilver)
 ("\\.gz$" all-the-icons-octicon "file-binary" :v-adjust 0.0 :face all-the-icons-lmaroon)
 ("\\.zip$" all-the-icons-octicon "file-zip" :v-adjust 0.0 :face all-the-icons-lmaroon)
 ("\\.7z$" all-the-icons-octicon "file-zip" :v-adjust 0.0 :face all-the-icons-lmaroon)
 ("\\.dat$" all-the-icons-faicon "bar-chart" :face all-the-icons-cyan :height 0.9)
 ("~$" all-the-icons-octicon "lock" :v-adjust 0.0 :face all-the-icons-maroon)
 ("\\.dmg$" all-the-icons-octicon "tools" :v-adjust 0.0 :face all-the-icons-lsilver)
 ("\\.dll$" all-the-icons-faicon "cogs" :face all-the-icons-silver)
 ("\\.DS_STORE$" all-the-icons-faicon "cogs" :face all-the-icons-silver)
 ("\\.scpt$" all-the-icons-fileicon "apple" :face all-the-icons-pink)
 ("\\.aup$" all-the-icons-fileicon "audacity" :face all-the-icons-yellow)
 ("\\.elm" all-the-icons-fileicon "elm" :face all-the-icons-blue)
 ("\\.erl$" all-the-icons-alltheicon "erlang" :face all-the-icons-red :v-adjust -0.1 :height 0.9)
 ("\\.hrl$" all-the-icons-alltheicon "erlang" :face all-the-icons-dred :v-adjust -0.1 :height 0.9)
 ("\\.eex$" all-the-icons-alltheicon "elixir" :face all-the-icons-lorange :v-adjust -0.1 :height 0.9)
 ("\\.ex$" all-the-icons-alltheicon "elixir" :face all-the-icons-lpurple :v-adjust -0.1 :height 0.9)
 ("\\.exs$" all-the-icons-alltheicon "elixir" :face all-the-icons-lred :v-adjust -0.1 :height 0.9)
 ("^mix.lock$" all-the-icons-alltheicon "elixir" :face all-the-icons-lyellow :v-adjust -0.1 :height 0.9)
 ("\\.java$" all-the-icons-alltheicon "java" :height 1.0 :face all-the-icons-purple)
 ("\\.go$" all-the-icons-alltheicon "go" :height 1.0 :face all-the-icons-blue)
 ("\\.mp3$" all-the-icons-faicon "volume-up" :face all-the-icons-dred)
 ("\\.wav$" all-the-icons-faicon "volume-up" :face all-the-icons-dred)
 ("\\.m4a$" all-the-icons-faicon "volume-up" :face all-the-icons-dred)
 ("\\.jl$" all-the-icons-fileicon "julia" :v-adjust 0.0 :face all-the-icons-purple)
 ("\\.matlab$" all-the-icons-fileicon "matlab" :face all-the-icons-orange)
 ("\\.nix$" all-the-icons-fileicon "nix" :face all-the-icons-blue)
 ("\\.p[ml]$" all-the-icons-alltheicon "perl" :face all-the-icons-lorange)
 ("\\.pl6$" all-the-icons-fileicon "perl6" :face all-the-icons-cyan)
 ("\\.pm6$" all-the-icons-fileicon "perl6" :face all-the-icons-pink)
 ("\\.pod$" all-the-icons-alltheicon "perldocs" :height 1.2 :face all-the-icons-lgreen)
 ("\\.php$" all-the-icons-fileicon "php" :face all-the-icons-lsilver)
 ("\\.pony$" all-the-icons-fileicon "pony" :face all-the-icons-maroon)
 ("\\.ps1$" all-the-icons-fileicon "powershell" :face all-the-icons-blue)
 ("\\.prol?o?g?$" all-the-icons-alltheicon "prolog" :height 1.1 :face all-the-icons-lmaroon)
 ("\\.py$" all-the-icons-alltheicon "python" :height 1.0 :face all-the-icons-dblue)
 ("\\.rkt$" all-the-icons-fileicon "racket" :height 1.2 :face all-the-icons-red)
 ("^Gemfile\\(\\.lock\\)?$" all-the-icons-alltheicon "ruby-alt" :face all-the-icons-red)
 ("\\.gem$" all-the-icons-alltheicon "ruby-alt" :face all-the-icons-red)
 ("_?test\\.rb$" all-the-icons-fileicon "test-ruby" :height 1.0 :v-adjust 0.0 :face all-the-icons-red)
 ("_?test_helper\\.rb$" all-the-icons-fileicon "test-ruby" :height 1.0 :v-adjust 0.0 :face all-the-icons-dred)
 ("_?spec\\.rb$" all-the-icons-fileicon "test-ruby" :height 1.0 :v-adjust 0.0 :face all-the-icons-red)
 ("_?spec_helper\\.rb$" all-the-icons-fileicon "test-ruby" :height 1.0 :v-adjust 0.0 :face all-the-icons-dred)
 ("\\.rb$" all-the-icons-octicon "ruby" :v-adjust 0.0 :face all-the-icons-lred)
 ("\\.rs$" all-the-icons-alltheicon "rust" :height 1.2 :face all-the-icons-maroon)
 ("\\.rlib$" all-the-icons-alltheicon "rust" :height 1.2 :face all-the-icons-dmaroon)
 ("\\.r[ds]?x?$" all-the-icons-fileicon "R" :face all-the-icons-lblue)
 ("\\.sbt$" all-the-icons-fileicon "sbt" :face all-the-icons-red)
 ("\\.scala$" all-the-icons-alltheicon "scala" :face all-the-icons-red)
 ("\\.scm$" all-the-icons-fileicon "scheme" :height 1.2 :face all-the-icons-red)
 ("\\.swift$" all-the-icons-alltheicon "swift" :height 1.0 :v-adjust -0.1 :face all-the-icons-green)

 ("-?spec\\." all-the-icons-fileicon "test-generic" :height 1.0 :v-adjust 0.0 :face all-the-icons-dgreen)
 ("-?test\\." all-the-icons-fileicon "test-generic" :height 1.0 :v-adjust 0.0 :face all-the-icons-dgreen)
 ("\\.tf\\(vars\\|state\\)?$" all-the-icons-fileicon "terraform" :height 1.0 :face all-the-icons-purple-alt)
 ("\\.v$" all-the-icons-fileicon "verilog" :height 1.0 :v-adjust -0.2 :face all-the-icons-red)
 ("\\.vams$" all-the-icons-fileicon "verilog" :height 1.0 :v-adjust -0.2 :face all-the-icons-red)
 ("\\.sv$" all-the-icons-fileicon "verilog" :height 1.0 :v-adjust -0.2 :face all-the-icons-red)
 ("\\.sva$" all-the-icons-fileicon "verilog" :height 1.0 :v-adjust -0.2 :face all-the-icons-red)
 ("\\.svh$" all-the-icons-fileicon "verilog" :height 1.0 :v-adjust -0.2 :face all-the-icons-red)
 ("\\.svams$" all-the-icons-fileicon "verilog" :height 1.0 :v-adjust -0.2 :face all-the-icons-red)
 ("\\.vhd$" all-the-icons-fileicon "vhdl" :face all-the-icons-blue)
 ("\\.vhdl$" all-the-icons-fileicon "vhdl" :face all-the-icons-blue)
 ("\\.vhms$" all-the-icons-fileicon "vhdl" :face all-the-icons-blue)
 ("\\.cabal$" all-the-icons-fileicon "cabal" :face all-the-icons-lblue)
 ("\\.kt$" all-the-icons-fileicon "kotlin" :face all-the-icons-orange)
 ("\\.kts$" all-the-icons-fileicon "kotlin" :face all-the-icons-orange)
 ("\\.nim$" all-the-icons-fileicon "nimrod" :face all-the-icons-yellow)
 ("\\.nims$" all-the-icons-fileicon "nimrod" :face all-the-icons-yellow)
 ("\\.sql$" all-the-icons-octicon "database" :face all-the-icons-silver)
 ("\\.styles$" all-the-icons-material "style" :face all-the-icons-red)
 ("\\.lua$" all-the-icons-fileicon "lua" :face all-the-icons-dblue)
 ("\\.adoc$" all-the-icons-fileicon "asciidoc" :face all-the-icons-lblue)
 ("\\.asciidoc$" all-the-icons-fileicon "asciidoc" :face all-the-icons-lblue)
 ("\\.pp$" all-the-icons-fileicon "puppet" :face all-the-icons-yellow)
 ("\\.j2$" all-the-icons-fileicon "jinja" :face all-the-icons-silver)
 ("\\.jinja2$" all-the-icons-fileicon "jinja" :face all-the-icons-silver)
 ("\\.dockerfile$" all-the-icons-fileicon "dockerfile" :face all-the-icons-cyan)
 ("\\.vagrantfile$" all-the-icons-fileicon "vagrant" :face all-the-icons-blue)
 ("\\.c$" all-the-icons-alltheicon "c-line" :face all-the-icons-blue)
 ("\\.h$" all-the-icons-alltheicon "c-line" :face all-the-icons-purple)
 ("\\.m$" all-the-icons-fileicon "apple" :v-adjust 0.0 :height 1.0)
 ("\\.mm$" all-the-icons-fileicon "apple" :v-adjust 0.0 :height 1.0)
 ("\\.c\\(c\\|pp\\|xx\\)$" all-the-icons-alltheicon "cplusplus-line" :v-adjust -0.2 :face all-the-icons-blue)
 ("\\.h\\(h\\|pp\\|xx\\)$" all-the-icons-alltheicon "cplusplus-line" :v-adjust -0.2 :face all-the-icons-purple)
 ("\\.csx?$" all-the-icons-alltheicon "csharp-line" :face all-the-icons-dblue)
 ("\\.cljc?$" all-the-icons-alltheicon "clojure-line" :height 1.0 :face all-the-icons-blue :v-adjust 0.0)
 ("\\.cljs$" all-the-icons-fileicon "cljs" :height 1.0 :face all-the-icons-dblue :v-adjust 0.0)
 ("\\.coffee$" all-the-icons-alltheicon "coffeescript" :height 1.0 :face all-the-icons-maroon)
 ("\\.iced$" all-the-icons-alltheicon "coffeescript" :height 1.0 :face all-the-icons-lmaroon)
 ("\\.dart$" all-the-icons-fileicon "dart" :height 1.0 :face all-the-icons-blue :v-adjust 0.0)
 ("^MERGE_" all-the-icons-octicon "git-merge" :v-adjust 0.0 :face all-the-icons-red)
 ("^COMMIT_EDITMSG" all-the-icons-octicon "git-commit" :v-adjust 0.0 :face all-the-icons-red)
 ("\\.cl$" all-the-icons-fileicon "clisp" :face all-the-icons-lorange)
 ("\\.l\\(isp\\)?$" all-the-icons-fileicon "lisp" :face all-the-icons-orange)
 ("\\.el$" all-the-icons-fileicon "elisp" :height 1.0 :v-adjust -0.2 :face all-the-icons-purple)
 ("\\.css$" all-the-icons-alltheicon "css3" :face all-the-icons-yellow)
 ("\\.scss$" all-the-icons-alltheicon "sass" :face all-the-icons-pink)
 ("\\.sass$" all-the-icons-alltheicon "sass" :face all-the-icons-dpink)
 ("\\.less$" all-the-icons-alltheicon "less" :height 0.8 :face all-the-icons-dyellow)
 ("\\.postcss$" all-the-icons-fileicon "postcss" :face all-the-icons-dred)
 ("\\.sss$" all-the-icons-fileicon "postcss" :face all-the-icons-dred)
 ("\\.styl$" all-the-icons-alltheicon "stylus" :face all-the-icons-lgreen)
 ("stylelint" all-the-icons-fileicon "stylelint" :face all-the-icons-lyellow)
 ("\\.csv$" all-the-icons-octicon "graph" :v-adjust 0.0 :face all-the-icons-dblue)
 ("\\.hs$" all-the-icons-alltheicon "haskell" :height 1.0 :face all-the-icons-red)
 ("\\.chs$" all-the-icons-alltheicon "haskell" :height 1.0 :face all-the-icons-red)
 ("\\.lhs$" all-the-icons-alltheicon "haskell" :height 1.0 :face all-the-icons-red)
 ("\\.hsc$" all-the-icons-alltheicon "haskell" :height 1.0 :face all-the-icons-red)
 ("\\.inky-haml$" all-the-icons-fileicon "haml" :face all-the-icons-lyellow)
 ("\\.haml$" all-the-icons-fileicon "haml" :face all-the-icons-lyellow)
 ("\\.html?$" all-the-icons-alltheicon "html5" :face all-the-icons-orange)
 ("\\.inky-erb?$" all-the-icons-alltheicon "html5" :face all-the-icons-lred)
 ("\\.erb$" all-the-icons-alltheicon "html5" :face all-the-icons-lred)
 ("\\.hbs$" all-the-icons-fileicon "moustache" :face all-the-icons-green)
 ("\\.inky-slim$" all-the-icons-octicon "dashboard" :v-adjust 0.0 :face all-the-icons-yellow)
 ("\\.slim$" all-the-icons-octicon "dashboard" :v-adjust 0.0 :face all-the-icons-yellow)
 ("\\.jade$" all-the-icons-fileicon "jade" :face all-the-icons-red)
 ("\\.pug$" all-the-icons-fileicon "pug-alt" :face all-the-icons-red)
 ("^gulpfile" all-the-icons-alltheicon "gulp" :height 1.0 :face all-the-icons-lred)
 ("^gruntfile" all-the-icons-alltheicon "grunt" :height 1.0 :v-adjust -0.1 :face all-the-icons-lyellow)
 ("^webpack" all-the-icons-fileicon "webpack" :face all-the-icons-lblue)
 ("\\.d3\\.?js" all-the-icons-alltheicon "d3" :height 0.8 :face all-the-icons-lgreen)
 ("\\.re$" all-the-icons-fileicon "reason" :height 1.0 :face all-the-icons-red-alt)
 ("\\.rei$" all-the-icons-fileicon "reason" :height 1.0 :face all-the-icons-dred)
 ("\\.ml$" all-the-icons-fileicon "ocaml" :height 1.0 :face all-the-icons-lpink)
 ("\\.mli$" all-the-icons-fileicon "ocaml" :height 1.0 :face all-the-icons-dpink)
 ("\\.ico$" all-the-icons-octicon "file-media" :v-adjust 0.0 :face all-the-icons-blue)
 ("\\.png$" all-the-icons-octicon "file-media" :v-adjust 0.0 :face all-the-icons-orange)
 ("\\.gif$" all-the-icons-octicon "file-media" :v-adjust 0.0 :face all-the-icons-green)
 ("\\.jpe?g$" all-the-icons-octicon "file-media" :v-adjust 0.0 :face all-the-icons-dblue)
 ("\\.svg$" all-the-icons-alltheicon "svg" :height 0.9 :face all-the-icons-lgreen)
 ("\\.mov" all-the-icons-faicon "film" :face all-the-icons-blue)
 ("\\.mp4" all-the-icons-faicon "film" :face all-the-icons-blue)
 ("\\.ogv" all-the-icons-faicon "film" :face all-the-icons-dblue)
 ("\\.mkv" all-the-icons-faicon "film" :face all-the-icons-blue)
 ("\\.webm" all-the-icons-faicon "film" :face all-the-icons-blue)
 ("\\.ttf$" all-the-icons-fileicon "font" :v-adjust 0.0 :face all-the-icons-dcyan)
 ("\\.woff2?$" all-the-icons-fileicon "font" :v-adjust 0.0 :face all-the-icons-cyan)
 ("\\.pdf" all-the-icons-octicon "file-pdf" :v-adjust 0.0 :face all-the-icons-dred)
 ("\\.te?xt" all-the-icons-octicon "file-text" :v-adjust 0.0 :face all-the-icons-cyan)
 ("\\.doc[xm]?$" all-the-icons-fileicon "word" :face all-the-icons-blue)
 ("\\.texi?$" all-the-icons-fileicon "tex" :face all-the-icons-lred)
 ("\\.md$" all-the-icons-octicon "markdown" :v-adjust 0.0 :face all-the-icons-lblue)
 ("\\.bib$" all-the-icons-fileicon "bib" :face all-the-icons-maroon)
 ("\\.org$" all-the-icons-fileicon "org" :face all-the-icons-lgreen)
 ("\\.pp[st]$" all-the-icons-fileicon "powerpoint" :face all-the-icons-orange)
 ("\\.pp[st]x$" all-the-icons-fileicon "powerpoint" :face all-the-icons-red)
 ("\\.knt$" all-the-icons-fileicon "powerpoint" :face all-the-icons-cyan)
 ("bookmark" all-the-icons-octicon "bookmark" :height 1.1 :v-adjust 0.0 :face all-the-icons-lpink)
 ("\\.cache$" all-the-icons-octicon "database" :height 1.0 :v-adjust 0.0 :face all-the-icons-green)
 ("^\\*scratch\\*$" all-the-icons-faicon "sticky-note" :face all-the-icons-lyellow)
 ("^\\*scratch.*" all-the-icons-faicon "sticky-note" :face all-the-icons-yellow)
 ("^\\*new-tab\\*$" all-the-icons-material "star" :face all-the-icons-cyan)
 ("^\\." all-the-icons-octicon "gear" :v-adjust 0.0)
 (".?" all-the-icons-faicon "file-o" :v-adjust 0.0 :face all-the-icons-dsilver)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
                                        ;         All icons to be used        ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(setq icons-definitions
      (append
       js-family-icons
       other-icons))

(setq all-the-icons-icon-alist icons-definitions)
